# _config.yml - thealternativeweddinggroup.co.uk

# Server Config

safe: true

timezone: Europe/London
encoding: "utf-8"

future: false

## Collections

collections:
  services:
    output: false

## Sass

sass:
  sass_dir: "_scss"
  style: :compressed

## Conversion

markdown: kramdown
highlighter: pygments
lsi: false
excerpt_separator: "\n\n"

## Backwards-compatibility
relative_permalinks: false

# Site Config

name: The Alternative Wedding Group

url:
static: /static
media: /media

## Analytics

google_analytics_id:

## Meta

meta:
  author: author
  description: ""
  keywords:
    - "Alternative Wedding Group"
